package se.yrgo.dataaccess;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import javax.sql.DataSource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

import se.yrgo.domain.Call;
import se.yrgo.domain.Customer;

@Repository("customerDao")
public class CustomerDaoJdbcTemplateImpl implements CustomerDao {

    private JdbcTemplate template;

    // Spring injicerar DataSource via denna setter
    @Autowired
    public void setDataSource(DataSource dataSource) {
        this.template = new JdbcTemplate(dataSource);
        createTables();
    }

    /**
     * Skapar tabellerna customer och customer_call.
     * "CALL" är ett ord i HSQLDB – tabellen heter customer_call.
     */
    public void createTables() {
        try {
            template.update(
                    "CREATE TABLE customer (" +
                            "  customer_id   VARCHAR(50)  PRIMARY KEY, " +
                            "  company_name  VARCHAR(100) NOT NULL, " +
                            "  notes         VARCHAR(255) " +
                            ")"
            );
        } catch (org.springframework.jdbc.BadSqlGrammarException e) {
            System.out.println("Tabellen customer finns redan.");
        }

        try {
            template.update(
                    "CREATE TABLE customer_call (" +
                            "  id           INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                            "  customer_id  VARCHAR(50) NOT NULL, " +
                            "  notes        VARCHAR(255), " +
                            "  FOREIGN KEY (customer_id) REFERENCES customer(customer_id) " +
                            ")"
            );
        } catch (org.springframework.jdbc.BadSqlGrammarException e) {
            System.out.println("Tabellen customer_call finns redan.");
        }
    }

    @Override
    public void create(Customer customer) {
        template.update(
                "INSERT INTO customer (customer_id, company_name, notes) VALUES (?, ?, ?)",
                customer.getCustomerId(),
                customer.getCompanyName(),
                customer.getNotes()
        );
    }

    @Override
    public Customer getById(String customerId) throws RecordNotFoundException {
        List<Customer> results = template.query(
                "SELECT customer_id, company_name, notes FROM customer WHERE customer_id = ?",
                new CustomerRowMapper(),
                customerId
        );
        if (results.isEmpty()) {
            throw new RecordNotFoundException("Customer not found: " + customerId);
        }
        return results.get(0);
    }

    @Override
    public List<Customer> getByName(String name) {
        return template.query(
                "SELECT customer_id, company_name, notes FROM customer WHERE LOWER(company_name) LIKE ?",
                new CustomerRowMapper(),
                "%" + name.toLowerCase() + "%"
        );
    }

    @Override
    public void update(Customer customer) throws RecordNotFoundException {
        int rows = template.update(
                "UPDATE customer SET company_name = ?, notes = ? WHERE customer_id = ?",
                customer.getCompanyName(),
                customer.getNotes(),
                customer.getCustomerId()
        );
        if (rows == 0) {
            throw new RecordNotFoundException("Customer not found: " + customer.getCustomerId());
        }
    }

    @Override
    public void delete(Customer customer) throws RecordNotFoundException {
        // Ta bort relaterade samtal först (pga foreign key)
        template.update("DELETE FROM customer_call WHERE customer_id = ?",
                customer.getCustomerId());

        int rows = template.update(
                "DELETE FROM customer WHERE customer_id = ?",
                customer.getCustomerId()
        );
        if (rows == 0) {
            throw new RecordNotFoundException("Customer not found: " + customer.getCustomerId());
        }
    }

    @Override
    public List<Customer> getAllCustomers() {
        return template.query(
                "SELECT customer_id, company_name, notes FROM customer",
                new CustomerRowMapper()
        );
    }

    @Override
    public Customer getFullCustomerDetail(String customerId) throws RecordNotFoundException {
        // Fråga 1: Hämta kunden
        Customer customer = getById(customerId);

        // Fråga 2: Hämta alla samtal för kunden
        List<Call> calls = template.query(
                "SELECT notes FROM customer_call WHERE customer_id = ?",
                new CallRowMapper(),
                customerId
        );

        // Koppla samtalen till kunden
        customer.setCalls(calls);
        return customer;
    }

    @Override
    public void addCall(Call newCall, String customerId) throws RecordNotFoundException {
        // Kontrollera att kunden existerar
        getById(customerId);

        template.update(
                "INSERT INTO customer_call (customer_id, notes) VALUES (?, ?)",
                customerId,
                newCall.getNotes()
        );
    }

    // RowMapper för Customer
    private static class CustomerRowMapper implements RowMapper<Customer> {
        @Override
        public Customer mapRow(ResultSet rs, int rowNum) throws SQLException {
            return new Customer(
                    rs.getString("customer_id"),
                    rs.getString("company_name"),
                    rs.getString("notes")
            );
        }
    }

    // RowMapper för Call
    private static class CallRowMapper implements RowMapper<Call> {
        @Override
        public Call mapRow(ResultSet rs, int rowNum) throws SQLException {
            return new Call(
                    rs.getString("notes")
            );
        }
    }
}